
services:
  - type: web
    name: springboot-app
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d3p2btc9c44c738khig0-a.oregon-postgres.render.com/temporaldb_fjzr
      - key: SPRING_DATASOURCE_USERNAME
        value: temporaldb_fjzr_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: xUG989zR5PzoHJnG3H3jzTf7a1wG1G7N
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: true
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect
